Update dotnet.yml

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -19,11 +19,24 @@ jobs:
 
     - name: Setup MSBuild
       uses: microsoft/setup-msbuild@v1.0.2
+      
+    - name: Set default value for status variable
+      run: echo "status=success" >> $GITHUB_ENV
 
     - name: Restore dependencies
       run: |
         nuget restore dev_staging_spaon
-
+        restore_status=$?
+        if [ $restore_status -ne 0 ]; then
+          echo "status=failure" >> $GITHUB_ENV
+          
     - name: Build
       run: |
         msbuild /p:Configuration=Release dev_staging_spaon
+        build_status=$?
+        if [ $build_status -ne 0 ]; then
+          echo "status=failure" >> $GITHUB_ENV
+          
+    - name: Prevent push to main on failure
+      if: env.status == 'failure'
+      run: exit 1
